version: "3.8"

services:
  bot:
    build: .
    container_name: linkedin-bot
    environment:
      - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
      - LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    volumes:
      - .:/app
    command: python client_interface.py
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - linkedin_bot_network

  database:
    image: sqlite3
    container_name: linkedin-db
    volumes:
      - sqlite_data:/var/lib/sqlite3
    networks:
      - linkedin_bot_network

  test:
    build: .
    container_name: linkedin-bot-tests
    volumes:
      - .:/app
    command: pytest tests/
    networks:
      - linkedin_bot_network

networks:
  linkedin_bot_network:
    driver: bridge

volumes:
  sqlite_data:
